server:
  port: 8888
spring:
  application:
    name: elastic-demo
  datasource:
    url: jdbc:mysql://localhost:3306/elastic_demo?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456