server:
  port: 10003
spring:
  application:
    name: user-nacos
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_micro?useUnicode=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ #集群名称
        namespace: edc365f6-2792-4866-b84a-236fa1f51a8e


mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    web: trace
    sql: trace