server:
  port: 10006
spring:
  application:
    name: order-nacos
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_micro?useUnicode=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: edc365f6-2792-4866-b84a-236fa1f51a8e #环境隔离，不同环境的服务之间不能拉取，无法访问
        ephemeral: false #默认true 临时实例，false 非临时实例，非临时实例下线后不会被nacos service 剔出
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    web: trace
    sql: trace
feign:
  client:
    config:
      default: #default 为开启全局日志 ，可以写具体服务名
        loggerLevel: basic #日志范围
  httpclient:
    enabled: true #开启http链接池
    max-connections: 200
    max-connections-per-route: 50