server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: edc365f6-2792-4866-b84a-236fa1f51a8e
    gateway:
      #解决跨域问题
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: #允许那些网站的跨域请求
              - "http://localhost：8080"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "OPTIONS"
              - "DELETE"
            allowedHeaders: "*"
            allowCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期

      routes:
        - id: user-service
          uri: lb://user-nacos #路由的目标地址
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order-nacos
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=name, cpy
      default-filters: #对所有路由有效
        - AddRequestHeader=name, cpy