server:
  port: 10002
spring:
  application:
    name: order-eureka
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_micro?useUnicode=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eager-load: #ribbon默认是懒加载，
    enabled: true  #非懒加载
    clients:  #指定服务名
    - user-eureka
